### ISSUE TITLE
Option of Access token authentication for Jira is not present

### ISSUE THREAD

**Issue by bovem** [reportportal/service-jira#21]
We are trying to integrate our private report portal instance with Jira (also private instance) but the integration tab only allows for "basic" authentication i.e. there is no option to use access token (provided by Jira).
![image](https://user-images.githubusercontent.com/29746858/154206704-b9eb0e81-2e6d-4b71-a67e-947041a13d2d.png)
@vipin3699

**Comment by DzmitryHumianiuk** [comment]
done.
